# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
tasks:
  - init: |
      cd src
      yarn
  - command: |
      cd src
      yarn start
ports:
  - port: 3000
    onOpen: open-preview
