name: build site
on:
  push:
    branches:
      - main
      - feature/github_pages

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    name: Build docusaurus Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: install yarn
        run: npm i -g --force yarn
      - name: restore yarn
        run: |
          cd $GITHUB_WORKSPACE/src
          yarn install
      - name: yarn build
        run: |
          cd $GITHUB_WORKSPACE/src
          yarn run build
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: icnaming@gmail.com
          build_dir: src/build
          cname: docs.icnaming.com
